# Generated by Django 4.0.4 on 2023-04-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0015_alter_rfidinfo_times'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datainfo',
            old_name='illumination',
            new_name='co2',
        ),
        migrations.RenameField(
            model_name='rfidinfo',
            old_name='uid',
            new_name='warn',
        ),
        migrations.AddField(
            model_name='datainfo',
            name='light',
            field=models.CharField(default=4, max_length=64),
        ),
    ]
