# Generated by Django 4.0.4 on 2023-04-10 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataInfo', '0016_rename_illumination_datainfo_co2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datainfo',
            name='time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
